export const defaultSettings = {
  rotateJobs: true,
  jobDelayMin: 0,
  jobDelayMax: 0,
  setWearDelay: 4,
  healthStop: 10,
  addEnergy: false,
  addMotivation: false,
  addHealth: false,
  useEnergyAt: 40,
  useHealthAt: 60,
  consumablesAutoUse: true,
  consumablesWatcherMs: 5000,
  jobStateNudge: true,
  nudgeDelayMs: 300,
  autoRefreshAfterBatch: false,
  refreshDelayMs: 1200,
  autoResumeAfterRefresh: true,
  resumeMaxAgeMinutes: 10,
  autoBankEnabled: false,
  autoBankThreshold: 25000,
  autoBankTownId: 733,
  autoBankWalkSet: -1,
  autoBankSafetyCooldownMs: 30000,
  autoCaptureTowns: true,
  workingSetId: -1,
  backupSetId: -1,
  autoCaptureEnabled: true,
  autoCaptureDefaultStopMot: 75,
  autoCaptureDefaultSet: -2,
  autoCaptureNoDuplicates: true,
  autoCaptureNotify: true,
  hToken: '',
};

export const searchKeys = {
  en_DK: { energy: 'Energy', energyText: 'Energy increase:', motivation: 'Work motivation', motivationText: 'Work motivation increase:', health: 'Health point bonus', healthText: 'Health point bonus:' },
  cs_CZ: { energy: 'Energie', energyText: 'Zvýšení energie:', motivation: 'Pracovní motivace', motivationText: 'Work motivation increase:', health: 'Bonus zdraví', healthText: 'Bonus zdraví:' },
  sk_SK: { energy: 'Energia', energyText: 'Zvýšenie energie:', motivation: 'Pracovnej motivácie', motivationText: 'Zvýšenie pracovnej motivácie:', health: 'Bonus bodov zdravia', healthText: 'Bonus bodov zdravia:' },
  pl_PL: { energy: 'Wzrost energii:', energyText: 'Wzrost energii:', motivation: 'Zwiększenie motywacji do pracy:', motivationText: 'Zwiększenie motywacji do pracy:', health: 'Bonus Punktów życia:', healthText: 'Bonus Punktów życia:' },
  hu_HU: { energy: 'Energia növekedése:', energyText: 'Energia növekedése:', motivation: 'Munka motiváció növelése:', motivationText: 'Munka motiváció növelése:', health: 'Életerő bónusz', healthText: 'Életerő bónusz:' },
  ro_RO: { energy: 'Energie mărită:', energyText: 'Energie mărită:', motivation: 'Creştere a motivaţiei de muncă:', motivationText: 'Creştere a motivaţiei de muncă:', health: 'Puncte de viaţă:', healthText: 'Puncte de viaţă:' },
};
